language: minimal

dist: focal

python: 3.8

addons:
    apt:
        packages:
        - gcc-arm-none-eabi
        - libnewlib-arm-none-eabi
        - python3-pip

before_install:

install:
- pip3 install -r basicloader/requirements.txt
- pip3 install -r requirements.txt

before_script:

script:
- make -C basicloader && cd projects/ex-join && make && VARIANT=simul make test
